shell = "zsh"

[plugins.ohmyzsh-git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"
use = ["*.plugin.zsh"]

[plugins.ohmyzsh-pass]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/pass"
use = ["_pass"]
apply = ["fpath"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
